tam:
- - 0.0
  - 1.0
  - 1.0
  - 0.0
  - 0.0
- - 0.9999999999999744
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 0.9999999999999744
  - 0.9999999999999744
- - 0.0
  - 0.0
  - 0.0
  - -0.823999999999979
  - 0.8279999999999788
- - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.9340000000000002
  - -0.9520000000000001
  - 0.0
  - 0.0
