# Sensors

# Camera Forward
- ros_topic_name: "/nekton/camera_forward"
  gz_topic_name: "/nekton/camera_forward"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Sonar Forward
- ros_topic_name: "/nekton/sonar_forward"
  gz_topic_name: "/nekton/sonar_forward"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/nekton/imu"
  gz_topic_name: "/nekton/imu_0"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Pressure
- ros_topic_name: "/nekton/pressure"
  gz_topic_name: "/pressure_0"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS


# Thrusters

# Thruster 0
- ros_topic_name: "/nekton/thruster_0/cmd_thrust"
  gz_topic_name: "/model/nekton/joint/prop_joint_0/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 1
- ros_topic_name: "/nekton/thruster_1/cmd_thrust"
  gz_topic_name: "/model/nekton/joint/prop_joint_1/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 2
- ros_topic_name: "/nekton/thruster_2/cmd_thrust"
  gz_topic_name: "/model/nekton/joint/prop_joint_2/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 3
- ros_topic_name: "/nekton/thruster_3/cmd_thrust"
  gz_topic_name: "/model/nekton/joint/prop_joint_3/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 4
- ros_topic_name: "/nekton/thruster_4/cmd_thrust"
  gz_topic_name: "/model/nekton/joint/prop_joint_4/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ


# GZ Sim Parameters
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
