# Odometry (Only used for testing)
- ros_topic_name: "/nekton/odometry"
  gz_topic_name: "/model/nekton/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS
